application:
  bot:
    token: secret
  database:
    driver: h2
    protocol: file
    host:
    port:
    username: notifier-bot
    password: notifier-bot
    database: ~/h2/notifier-bot

logging:
  level:
    root: WARN
    dev.nk7: DEBUG
